[pytest]
filterwarnings =
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*:DeprecationWarning
    ignore:.*json_encoders is deprecated.*:DeprecationWarning
    ignore:.*Using `@model_validator` with mode='after' on a classmethod is deprecated.*:DeprecationWarning
    ignore:.*Support for class-based `config` is deprecated.*:DeprecationWarning
    ignore:.*`langchain-community` is being sunset.*:DeprecationWarning
    ignore::ibm_watsonx_ai.wml_resource.WatsonxAPIWarning
