import os
import random

TEAMS_48 = {
    "Uruguay": {
        "coach": "Marcelo Bielsa",
        "players": [
            "Fernando Muslera",
            "Santiago Mele",
            "Sergio Rochet",
            "Guillermo Varela",
            "Ronald Ara\u00fajo",
            "Sebast\u00edan C\u00e1ceres",
            "Mat\u00edas Vi\u00f1a",
            "Joaqu\u00edn Piquerez",
            "Maximiliano Ara\u00fajo",
            "Math\u00edas Olivera",
            "Santiago Bueno",
            "Jos\u00e9 Gim\u00e9nez",
            "Federico Valverde",
            "Giorgian De Arrascaeta",
            "Rodrigo Bentancur",
            "Manuel Ugarte",
            "Brian Rodr\u00edguez",
            "Rodrigo Zalazar",
            "Facundo Pellistri",
            "Emiliano Mart\u00ednez",
            "Juan Sanabria",
            "Nicolas de la Cruz",
            "Rodrigo Aguirre",
            "Darwin N\u00fa\u00f1ez",
            "Agust\u00edn Canobbio",
            "Federico Vi\u00f1as"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Germany": {
        "coach": "Julian Nagelsmann",
        "players": [
            "Oliver Baumann",
            "Manuel Neuer",
            "Alexander N\u00fcbel",
            "Jonathan Tah",
            "Waldemar Anton",
            "Antonio R\u00fcdiger",
            "David Raum",
            "Nico Schlotterbeck",
            "Malick Thiaw",
            "Nathaniel Brown",
            "Nadiem Amiri",
            "Joshua Kimmich",
            "Leon Goretzka",
            "Pascal Gro\u00df",
            "Florian Wirtz",
            "Felix Kalu Nmecha",
            "Angelo Stiller",
            "Jamal Musiala",
            "Aleksandar Pavlovi\u0107",
            "Assan Ou\u00e9draogo",
            "Kai Havertz",
            "Leroy San\u00e9",
            "Deniz Undav",
            "Jamie Leweling",
            "Nick Woltemade",
            "Maximilian Beier"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Spain": {
        "coach": "Luis de la Fuente",
        "players": [
            "David Raya",
            "Unai Sim\u00f3n",
            "Joan Garc\u00eda",
            "Aymeric Laporte",
            "Cucurella",
            "Alejandro Grimaldo",
            "Pedro Porro",
            "Eric Garc\u00eda",
            "Marc Pubill",
            "Pau Cubars\u00ed",
            "Fabi\u00e1n Ruiz",
            "Marcos Llorente",
            "Rodri",
            "Mikel Merino",
            "Dani Olmo",
            "Ferr\u00e1n Torres",
            "Mart\u00edn Zubimendi",
            "Pedri",
            "Pablo Gavira",
            "Mikel Oyarzabal",
            "\u00c1lex Baena",
            "Borja Iglesias",
            "Yeremi Pino",
            "Nico Williams",
            "Lamine Yamal",
            "V\u00edctor Mu\u00f1oz"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Paraguay": {
        "coach": "Gustavo Alfaro",
        "players": [
            "Gast\u00f3n Olveira",
            "Roberto Fern\u00e1ndez",
            "Orlando Gill",
            "Fabi\u00e1n Balbuena",
            "Gustavo G\u00f3mez",
            "J\u00fanior Alonso",
            "Omar Alderete",
            "Juan C\u00e1ceres",
            "Gustavo Vel\u00e1zquez",
            "Jos\u00e9 Canale",
            "Alexandro Maidana",
            "Andr\u00e9s Cubas",
            "Kaku",
            "Miguel Almir\u00f3n",
            "Mauricio",
            "Braian Ojeda",
            "Mat\u00edas Galarza",
            "Damian Bobadilla",
            "Diego G\u00f3mez",
            "Antonio Sanabria",
            "Gabriel \u00c1valos",
            "Isidro Pitta",
            "Ram\u00f3n Sosa",
            "Julio Enciso",
            "Gustavo Caballero",
            "Alex Arce"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Argentina": {
        "coach": "Lionel Scaloni",
        "players": [
            "G\u00e9ronimo Rulli",
            "Emiliano Mart\u00ednez",
            "Juan Musso",
            "Nicol\u00e1s Otamendi",
            "Nicol\u00e1s Tagliafico",
            "Gonzalo Montiel",
            "Christian Romero",
            "Facundo Medina",
            "Lisandro Mart\u00ednez",
            "Nahuel Molina",
            "Leonardo Balerdi",
            "Valentin Barco",
            "Rodrigo de Paul",
            "Leandro Paredes",
            "Giovani Lo Celso",
            "Exequiel Palacios",
            "Alexis Mac Allister",
            "Thiago Almada",
            "Enzo Fern\u00e1ndez",
            "Nico Paz",
            "Lionel Messi",
            "Lautaro Mart\u00ednez",
            "Nicol\u00e1s Gonz\u00e1lez",
            "Juli\u00e1n \u00c1lvarez",
            "Jos\u00e9 Manuel L\u00f3pez",
            "Giuliano Simeone"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Ghana": {
        "coach": "Carlos Queiroz",
        "players": [
            "Lawrence Ati-Zigi",
            "Joseph Anang",
            "Benjamin Asare",
            "Abdul Rahman Baba",
            "Derrick Luckassen",
            "Gideon Mensah",
            "Abdul Mumin",
            "Jerome Opoku",
            "Alidu Seidu",
            "Marvin Senaya",
            "Jonas Adjei Adjetey",
            "Kojo Peprah Oppong",
            "Thomas Partey",
            "Elisha Owusu",
            "Kwasi Sibo",
            "Augustine Boakye",
            "Caleb Yirenkyi",
            "Antoine Semenyo",
            "Brandon Thomas-Asante",
            "Jordan Ayew",
            "I\u00f1aki Williams",
            "Kamal Deen Sulemana",
            "Ernest Nuamah",
            "Abdul Issahaku",
            "Christopher Bonsu Baah",
            "Prince Adu"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Brazil": {
        "coach": "Carlo Ancelotti",
        "players": [
            "Weverton",
            "Alisson Becker",
            "Ederson",
            "Roger Iba\u00f1ez",
            "Bremer",
            "Alex Sandro",
            "Marquinhos",
            "Douglas Santos",
            "Danilo Luiz da Silva",
            "L\u00e9o Pereira",
            "Gabriel Magalh\u00e3es",
            "Wesley",
            "Lucas Paquet\u00e1",
            "Bruno Guimar\u00e3es",
            "Casemiro",
            "Fabinho",
            "Danilo dos Santos de Oliveira",
            "Vinicius Junior",
            "Neymar",
            "Matheus Cunha",
            "Raphinha",
            "Martinelli",
            "Thiago",
            "Luiz Henrique",
            "Endrick",
            "Rayan"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Portugal": {
        "coach": "Roberto Mart\u00ednez",
        "players": [
            "Jos\u00e9 S\u00e1",
            "Rui Silva",
            "Diogo Costa",
            "Jo\u00e3o Cancelo",
            "R\u00faben Dias",
            "N\u00e9lson Semedo",
            "Diogo Dalot",
            "Matheus Nunes",
            "Nuno Mendes",
            "Gon\u00e7alo In\u00e1cio",
            "Tomas Araujo",
            "Renato Veiga",
            "Bernardo Silva",
            "R\u00faben Neves",
            "Bruno Fernandes",
            "Gon\u00e7alo Guedes",
            "Samuel Almeida Costa",
            "Vitinha",
            "Joao Neves",
            "Cristiano Ronaldo",
            "Pedro Neto",
            "Rafael Le\u00e3o",
            "Trinc\u00e3o",
            "Jo\u00e3o F\u00e9lix",
            "Gon\u00e7alo Ramos",
            "Francisco Concei\u00e7\u00e3o"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Japan": {
        "coach": "Hajime Moriyasu",
        "players": [
            "Keisuke \u014csako",
            "Zion Suzuki",
            "Tomoki Hayakawa",
            "Y\u016bto Nagatomo",
            "Takehiro Tomiyasu",
            "Hiroki Ito",
            "Yukinari Sugawara",
            "Ko Itakura",
            "Shogo Taniguchi",
            "Ayumu Seko",
            "Tsuyoshi Watanabe",
            "Junnosuke Suzuki",
            "Wataru End\u014d",
            "Daichi Kamada",
            "Takefusa Kubo",
            "Keito Nakamura",
            "Ao Tanaka",
            "Kaishu Sano",
            "Yuito Suzuki",
            "Ritsu Doan",
            "Daizen Maeda",
            "Koki Ogawa",
            "Junya Ito",
            "Ayase Ueda",
            "Kento Shiogai",
            "Keisuke Goto"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Mexico": {
        "coach": "Javier Aguirre",
        "players": [
            "Guillermo Ochoa",
            "Carlos Acevedo",
            "Jos\u00e9 Rangel",
            "Jes\u00fas Gallardo",
            "C\u00e9sar Montes",
            "Johan V\u00e1squez",
            "Jorge S\u00e1nchez",
            "Israel Reyes",
            "Mateo Ch\u00e1vez",
            "Edson \u00c1lvarez",
            "Orbel\u00edn Pineda",
            "Luis Ch\u00e1vez",
            "Luis Romo",
            "Erik Lira",
            "\u00c1lvaro Fidalgo",
            "Brian Guti\u00e9rrez",
            "Obed Vargas",
            "Gilberto Mora",
            "Ra\u00fal Jim\u00e9nez",
            "Juli\u00e1n Qui\u00f1ones",
            "Roberto Alvarado",
            "Santiago Gim\u00e9nez",
            "Alexis Vega",
            "Guillermo Mart\u00ednez",
            "C\u00e9sar Huerta",
            "Armando Gonz\u00e1lez"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "England": {
        "coach": "Thomas Tuchel",
        "players": [
            "Jordan Pickford",
            "Dean Henderson",
            "James Trafford",
            "John Stones",
            "Dan Burn",
            "Ezri Konsa",
            "Reece James",
            "Djed Spence",
            "Marc Gu\u00e9hi",
            "Valentino Livramento",
            "Jarell Quansah",
            "Nico O'Reilly",
            "Jordan Henderson",
            "Eberechi Eze",
            "Anthony Gordon",
            "Declan Rice",
            "Morgan Rogers",
            "Elliot Anderson",
            "Jude Bellingham",
            "Kobbie Mainoo",
            "Marcus Rashford",
            "Ollie Watkins",
            "Ivan Toney",
            "Harry Kane",
            "Bukayo Saka",
            "Noni Madueke"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "United States": {
        "coach": "Mauricio Pochettino",
        "players": [
            "Matt Turner",
            "Matt Freese",
            "Chris Brady",
            "Antonee Robinson",
            "Tim Ream",
            "Miles Robinson",
            "Auston Trusty",
            "Mark McKenzie",
            "Joseph Scally",
            "Sergi\u00f1o Dest",
            "Chris Richards",
            "Alex Freeman",
            "Weston McKennie",
            "Alejandro Zendejas",
            "Cristian Roldan",
            "Tyler Adams",
            "Brenden Aaronson",
            "Gio Reyna",
            "Sebastian Berhalter",
            "Malik Tillman",
            "Christian Pulisic",
            "Tim Weah",
            "Haji Wright",
            "Ricardo Pepi",
            "Folarin Balogun",
            "Max Arfsten"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "South Korea": {
        "coach": "Hong Myungbo",
        "players": [
            "Seung-Gyu Kim",
            "Bum-keun Song",
            "Hyeon-woo Jo",
            "Min-Jae Kim",
            "Moon-hwan Kim",
            "Han-bum Lee",
            "Young-woo Seol",
            "Jin-seob Park",
            "Tae-hyeon Kim",
            "Gi-hyuk Lee",
            "Tae-seok Lee",
            "Cho Wi-Je",
            "Jens Castrop",
            "In-beom Hwang",
            "Dong-gyeong Lee",
            "Jae-sung Lee",
            "Jin-Gyu Kim",
            "Seung-Ho Paik",
            "Kang-in Lee",
            "Joon-ho Bae",
            "Hwang Heechan",
            "Heung-min Son",
            "Hyun-jun Yang",
            "Gue-Sung Cho",
            "Hyun-Gyu Oh",
            "Ji-sung Eom"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "France": {
        "coach": "Didier Deschamps",
        "players": [
            "Brice Samba",
            "Mike Maignan",
            "Robin Risser",
            "Theo Hern\u00e1ndez",
            "Lucas Digne",
            "Lucas Hern\u00e1ndez",
            "Jules Kound\u00e9",
            "Dayot Upamecano",
            "Ibrahima Konat\u00e9",
            "William Saliba",
            "Maxence Lacroix",
            "Malo Gusto",
            "N'Golo Kant\u00e9",
            "Adrien Rabiot",
            "Aur\u00e9lien Tchouameni",
            "Manu Kon\u00e9",
            "Rayan Cherki",
            "Maghnes Akliouche",
            "Desire Doue",
            "Warren Za\u00efre-Emery",
            "Jean-Philippe Mateta",
            "Ousmane Demb\u00e9l\u00e9",
            "Kylian Mbapp\u00e9",
            "Marcus Thuram-Ulien",
            "Michael Olise",
            "Bradley Barcola"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "South Africa": {
        "coach": "Hugo Broos",
        "players": [
            "Ronwen Williams",
            "Sipho Chaine",
            "Ricardo Goss",
            "Aubrey Modiba",
            "Nkosinathi Sibisi",
            "Khuliso Mudau",
            "Olwethu Makhanya",
            "Bradley Cross",
            "Samukelo Kabini",
            "Ime Okon",
            "Mbekezeli Mbokazi",
            "Khulumani Ndamane",
            "Tholo Matuludi",
            "Themba Zwane",
            "Teboho Mokoena",
            "Sphephelo Sithole",
            "Jayden Adams",
            "Thapelo Maseko",
            "Thalente Mbatha",
            "Kamogelo Sebelebele",
            "Lyle Foster",
            "Oswin Appollis",
            "Iqraam Rayners",
            "Evidence Makgopa",
            "Relebohile Mofokeng",
            "Tshepang Moremi"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Algeria": {
        "coach": "Vladimir Petkovi\u0107",
        "players": [
            "Luca Zidane",
            "Oussama Benbout",
            "Melvin Mastil",
            "A\u00efssa Mandi",
            "Rayan A\u00eft Nouri",
            "Ramy Bensebaini",
            "Samir Chergui",
            "Jaouen Hadjam",
            "Rafik Belghali",
            "Zin\u00e9dine Bela\u00efd",
            "Amine Tougai",
            "Achref Abada",
            "Nabil Bentaleb",
            "Houssem Aouar",
            "Hicham Boudaoui",
            "Ramiz Zerrouki",
            "Fares Cha\u00efbi",
            "Ibrahim Maza",
            "Yacine Titraoui",
            "Adil Boulbina",
            "Riyad Mahrez",
            "Amine Gouiri",
            "Mohammed Amoura",
            "Nadhir Benbouali",
            "Anis Moussa",
            "Far\u00e9s Ghedjemis"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Australia": {
        "coach": "Tony Popovi\u0107",
        "players": [
            "Maty Ryan",
            "Paul Izzo",
            "Patrick Beach",
            "Aziz Behich",
            "Milo\u0161 Degenek",
            "Kai Trewin",
            "Jacob Italiano",
            "Cameron Burgess",
            "Harry Souttar",
            "Jason Geria",
            "Jordan Bos",
            "Alessandro Circati",
            "Lucas Herrington",
            "Mathew Leckie",
            "Jackson Irvine",
            "Connor Metcalfe",
            "Ajdin Hrustic",
            "Aiden O'Neill",
            "Awer Mabil",
            "Cameron Devlin",
            "Paul Okon-Engstler",
            "Mohamed Toure",
            "Nishan Velupillay",
            "Cristian Volpato",
            "Nestor Irankunda",
            "Tete Yengi"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "New Zealand": {
        "coach": "Darren Bazeley",
        "players": [
            "Max Crocombe",
            "Michael Woud",
            "Alex Paulsen",
            "Liberato Cacace",
            "Tommy Smith",
            "Michael Boxall",
            "Francis De Vries",
            "Callan Elliot",
            "Tim Payne",
            "Nando Pijnaker",
            "Finn Surman",
            "Tyler Bindon",
            "Alex Rufer",
            "Sarpreet Singh",
            "Ryan Thomas",
            "Callum McCowatt",
            "Joe Bell",
            "Marko Stamenic",
            "Ben Old",
            "Kosta Barbarouses",
            "Chris Wood",
            "Ben Waine",
            "Elijah Just",
            "Matthew Garbett",
            "Lachlan Bayliss",
            "Jesse Randall"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Switzerland": {
        "coach": "Murat Yakin",
        "players": [
            "Gregor Kobel",
            "Yvon Mvogo",
            "Marvin Keller",
            "Manuel Akanji",
            "Ricardo Rodriguez",
            "Silvan Widmer",
            "Nico Elvedi",
            "Eray C\u00f6mert",
            "Miro Muheim",
            "Aurele Amenda",
            "Luca Jaquez",
            "Remo Freuler",
            "Granit Xhaka",
            "Denis Zakaria",
            "Michel Aebischer",
            "Djibril Sow",
            "Christian Fassnacht",
            "Ruben Vargas",
            "Ardon Jasari",
            "Fabian Rieder",
            "Johan Manzambi",
            "Breel Embolo",
            "Noah Okafor",
            "C\u00e9dric Itten",
            "Dan Ndoye",
            "Zeki Amdouni"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Ecuador": {
        "coach": "Sebasti\u00e1n Beccacece",
        "players": [
            "Hern\u00e1n Gal\u00edndez",
            "Gonzalo Valle",
            "Mois\u00e9s Ram\u00edrez",
            "\u00c1ngelo Preciado",
            "F\u00e9lix Torres",
            "Pervis Estupi\u00f1\u00e1n",
            "William Pacho",
            "Jackson Porozo",
            "Piero Hincapi\u00e9",
            "Joel Ordo\u00f1ez",
            "Yaimar Medina",
            "Alan Franco",
            "Jordy Alc\u00edvar",
            "Gonzalo Plata",
            "Mois\u00e9s Caicedo",
            "Pedro Vite",
            "Alan Minda",
            "Ray Paez",
            "Denil Castillo",
            "Jordy Caicedo",
            "Enner Valencia",
            "John Yeboah",
            "Anthony Valencia",
            "Nilson Angulo",
            "Kevin Rodr\u00edguez",
            "Jeremy"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Sweden": {
        "coach": "Graham Potter",
        "players": [
            "Kristoffer Nordfeldt",
            "Viktor Johansson",
            "Jacob Widell Zetterstr\u00f6m",
            "Victor Nilsson-Lindel\u00f6f",
            "Carl Starfelt",
            "Gabriel Gudmundsson",
            "Hjalmar Ekdal",
            "Eric Smith",
            "Daniel Svensson",
            "Gustaf Lagerbielke",
            "Isak Hien",
            "Herman Johansson",
            "Elliot Stroud",
            "Ken Sema",
            "Mattias Svanberg",
            "Jesper Karlstr\u00f6m",
            "Yasin Ayari",
            "Besfort Zeneli",
            "Taha Ali",
            "Lucas Bergvall",
            "Alexander Isak",
            "Viktor Gy\u00f6keres",
            "Gustaf Nilsson",
            "Benjamin Nygren",
            "Alexander Bernhardsson",
            "Anthony Elanga"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Czech Republic": {
        "coach": "Miroslav Koubek",
        "players": [
            "Jind\u0159ich Stan\u011bk",
            "Matej Kovar",
            "Luk\u00e1\u0161 Horn\u00ed\u010dek",
            "Jaroslav Zelen\u00fd",
            "Vladimir Coufal",
            "Tom\u00e1\u0161 Hole\u0161",
            "David Zima",
            "David Jur\u00e1sek",
            "Robin Hranac",
            "\u0160t\u011bp\u00e1n Chaloupek",
            "Ladislav Krej\u010d\u00ed",
            "Vladim\u00edr Darida",
            "Tom\u00e1\u0161 Sou\u010dek",
            "David Doud\u011bra",
            "Michal Sad\u00edlek",
            "Luk\u00e1\u0161 Provod",
            "Pavel \u0160ulc",
            "Luk\u00e1\u0161 \u010cerv",
            "Denis Vi\u0161insk\u00fd",
            "Alexandr Sojka",
            "Hugo Soch\u016frek",
            "Patrik Schick",
            "Tom\u00e1\u0161 Chor\u00fd",
            "Jan Kuchta",
            "Adam Hlo\u017eek",
            "Mojm\u00edr Chytil"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Croatia": {
        "coach": "Zlatko Dali\u0107",
        "players": [
            "Dominik Livakovi\u0107",
            "Ivor Pandur",
            "Dominik Kotarski",
            "Duje \u0106aleta-Car",
            "Marin Pongra\u010di\u0107",
            "Martin Erlic",
            "Josip Stani\u0161i\u0107",
            "Jo\u0161ko Gvardiol",
            "Josip \u0160utalo",
            "Luka Vu\u0161kovi\u0107",
            "Luka Modri\u0107",
            "Mateo Kova\u010di\u0107",
            "Mario Pa\u0161ali\u0107",
            "Nikola Vla\u0161i\u0107",
            "Nikola Moro",
            "Kristijan Jaki\u0107",
            "Luka Su\u010di\u0107",
            "Petar Sucic",
            "Martin Baturina",
            "Toni Fruk",
            "Andrej Kramari\u0107",
            "Ivan Peri\u0161i\u0107",
            "Ante Budimir",
            "Petar Musa",
            "Marco Pa\u0161ali\u0107",
            "Igor Matanovic"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Saudi Arabia": {
        "coach": "Giorgios Donis",
        "players": [
            "Mohammed Al Owais",
            "Nawaf Al Aqidi",
            "Ahmed Al Kassar",
            "Abdulelah Al Amri",
            "Saud Abdulhamid",
            "Ali Lajami",
            "Hassan Al Tambakti",
            "Hassan Kadesh",
            "Moteb Al Harbi",
            "Ali Majrashi",
            "Jehad Thakri",
            "Nawaf Boushal",
            "Salem Al Dawsari",
            "Abdullah Al Khaibari",
            "Nasser Al Dawsari",
            "Ayman Yahya",
            "Musab Al Juwayr",
            "Mohammed Kanno",
            "Ziyad Al-Johani",
            "Mohammed Abu Al Shamat",
            "Alaa Al Hejji",
            "Sultan Mandash",
            "Saleh Al Shehri",
            "Abdullah Al-Hamdan",
            "Khalid Al Ghannam",
            "Firas Al Brikan"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Tunisia": {
        "coach": "Herv\u00e9 Renard",
        "players": [
            "Aymen Dahmen",
            "Sabri Ben Hessen",
            "Abdelmouhib Chamakh",
            "Dylan Bronn",
            "Ali El Abdi",
            "Yan Valery",
            "Mortadha Ben Ouanes",
            "Omar Rekik",
            "Yassine Chikhaoui",
            "Montassar Talbi",
            "Moutaz Neffati",
            "Mohamed Amine Ben Hamida",
            "Adem Arous",
            "Ellyes Skhiri",
            "Rani Khedira",
            "Anis Ben Slimane",
            "Isma\u00ebl Gharbi",
            "Hannibal Mejbri",
            "Elias Achouri",
            "Hadj Mahmoud",
            "Sebastian Tounekti",
            "Firas Chaouat",
            "Elias Saad",
            "Hazem Mastouri",
            "Rayan Elloumi",
            "Khalil Ayari"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Turkey": {
        "coach": "Vincenzo Montella",
        "players": [
            "Mert G\u00fcnok",
            "Altay Bay\u0131nd\u0131r",
            "U\u011furcan \u00c7ak\u0131r",
            "\u00c7a\u011flar S\u00f6y\u00fcnc\u00fc",
            "Kaan Ayhan",
            "Ferdi Kad\u0131o\u011flu",
            "Mert M\u00fcld\u00fcr",
            "Zeki \u00c7elik",
            "Abd\u00fclkerim Bardakc\u0131",
            "Ozan Kabak",
            "Merih Demiral",
            "Samet Akayd\u0131n",
            "Evren Eren Elmal\u0131",
            "Salih \u00d6zcan",
            "Hakan \u00c7alhano\u011flu",
            "Orkun K\u00f6k\u00e7\u00fc",
            "\u0130smail Y\u00fcksek",
            "Arda Guler",
            "Oguz Aydin",
            "Baris Yilmaz",
            "\u0130rfan Kahveci",
            "Yunus Akg\u00fcn",
            "Muhammed Kerem Akt\u00fcrko\u011flu",
            "Deniz Gul",
            "Kenan Y\u0131ld\u0131z",
            "Can Uzun"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Senegal": {
        "coach": "Unknown Coach",
        "players": [
            "Edouard Mendy",
            "Yehvann Diouf",
            "Mory Diaw",
            "Ismail Jakobs",
            "Kalidou Koulibaly",
            "Moussa Niakhat\u00e9",
            "Abdoulaye Seck",
            "Antoine Mendy",
            "Mamadou Sarr",
            "El Hadji Diouf",
            "Pape Gueye",
            "Idrissa Gana Gu\u00e8ye",
            "Isma\u00efla Sarr",
            "Kr\u00e9pin Diatta",
            "Path\u00e9 Ciss",
            "Iliman Ndiaye",
            "Pape Sarr",
            "Habib Diarra",
            "Lamine Camara",
            "Bara Ndiaye",
            "Sadio Man\u00e9",
            "Cherif Ndiaye",
            "Nicolas Jackson",
            "Ahmadou Bamba Dieng",
            "Assane Diao",
            "Ibrahim M'Baye",
            "Pape Thiaw"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Belgium": {
        "coach": "Rudi Garcia",
        "players": [
            "Thibaut Courtois",
            "Senne Lammens",
            "Mike Penders",
            "Timothy Castagne",
            "Thomas Meunier",
            "Brandon Mechele",
            "Maxim De Cuyper",
            "Arthur Theate",
            "Koni De Winter",
            "Zeno Debast",
            "Nathan Ngoy",
            "Joaquin Seys",
            "Kevin De Bruyne",
            "Axel Witsel",
            "Youri Tielemans",
            "Dodi Lukebakio",
            "Alexis Saelemaekers",
            "Hans Vanaken",
            "Nicolas Raskin",
            "Jeremy Doku",
            "Amadou Onana",
            "Diego Moreira",
            "Romelu Lukaku",
            "Leandro Trossard",
            "Charles De Ketelaere",
            "Matias Fernandez-Pardo"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Morocco": {
        "coach": "Mohamed Ouahbi",
        "players": [
            "Munir Mohamedi",
            "Yassine Bounou",
            "Ahmed Reda Tagnaouti",
            "Achraf Hakimi",
            "Noussair Mazraoui",
            "Issa Diop",
            "Nayef Aguerd",
            "Anass Salah-Eddine",
            "Chadi Riad",
            "Redouane Halhal",
            "Zakaria El Ouahdi",
            "Youssef Belammari",
            "Sofyan Amrabat",
            "Brahim Diaz",
            "Azzedine Ounahi",
            "Ismael Saibari",
            "Neil El Aynaoui",
            "Bilal El Khannouss",
            "Chemsdine Talbi",
            "Ayyoub Bouaddi",
            "Samir El Mourabet",
            "Soufiane Rahimi",
            "Ayoub El Kaabi",
            "Abdessamad Ezzalzouli",
            "Gessime Yassine",
            "Ayoube Amaimouni-Echghouyab"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Austria": {
        "coach": "Ralf Rangnick",
        "players": [
            "Alexander Schlager",
            "Patrick Pentz",
            "Florian Wiegele",
            "David Alaba",
            "Stefan Posch",
            "Philipp Mwene",
            "Kevin Danso",
            "Marco Friedl",
            "Philipp Lienhart",
            "Michael Svoboda",
            "Alexander Prass",
            "David Affengruber",
            "Florian Grillitsch",
            "Alessandro Sch\u00f6pf",
            "Konrad Laimer",
            "Marcel Sabitzer",
            "Xaver Schlager",
            "Romano Schmid",
            "Christoph Baumgartner",
            "Nicolas  Seiwald",
            "Patrick Wimmer",
            "Carney Chukwuemeka",
            "Paul Wanner",
            "Michael Gregoritsch",
            "Marko Arnautovic",
            "Sa\u0161a Kalajd\u017ei\u0107"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Colombia": {
        "coach": "N\u00e9stor Lorenzo",
        "players": [
            "Camilo Vargas",
            "David Ospina",
            "\u00c1lvaro Montero",
            "Santiago Arias",
            "Johan Mojica",
            "Yerry Mina",
            "Davinson S\u00e1nchez",
            "Deiver Machado",
            "Daniel Mu\u00f1oz",
            "Jhon Lucum\u00ed",
            "Willer Ditta",
            "James Rodr\u00edguez",
            "Jefferson Lerma",
            "Jhon Arias",
            "Jorge Carrascal",
            "Kevin Casta\u00f1o",
            "Juan Quintero",
            "Jaminton Campaz",
            "Richard Rios",
            "Juan Portilla",
            "Gustavo Puerta",
            "Jhon C\u00f3rdoba",
            "Luis D\u00edaz",
            "Luis Su\u00e1rez",
            "Cucho Hern\u00e1ndez",
            "Carlos G\u00f3mez"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Egypt": {
        "coach": "Hossam Hassan",
        "players": [
            "Mohamed El Shenawy",
            "Mohamed Alaa",
            "Oufa Shobeir",
            "El Mahdi Soliman",
            "Karim Hafez",
            "Mohamed Hany",
            "Yasser Ibrahim",
            "Ahmed El Fotouh",
            "Mohamed Abdelmonem",
            "Rami Rabia",
            "Hossam Abdelmaguid",
            "Tarek Alaa",
            "Zizo",
            "Nabil Dunga",
            "Hamdy Fathy",
            "Trezeguet",
            "Emam Ashour",
            "Mohanad Lashin",
            "Marwan Attia",
            "Mahmoud Saber",
            "Mostafa Ziko",
            "Mohamed Salah",
            "Omar Marmoush",
            "Haissem Hassan",
            "Ibrahim Adel",
            "Hamza Abdelkarim"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Canada": {
        "coach": "Jesse Marsch",
        "players": [
            "Maxime Cr\u00e9peau",
            "Dayne St. Clair",
            "Owen Goodman",
            "Alphonso Davies",
            "Richie Laryea",
            "Alfie Jones",
            "Joel Waterman",
            "Derek Cornelius",
            "Alistair Johnston",
            "Moise Bombito",
            "Luc De Fougerolles",
            "Jonathan Osorio",
            "Stephen Eust\u00e1quio",
            "Mathieu Choini\u00e8re",
            "Tajon Buchanan",
            "Marcelo Flores",
            "Nathan-Dylan Saliba",
            "Ismael Kone",
            "Ali Ahmed",
            "Niko Sigur",
            "Jonathan David",
            "Cyle Larin",
            "Liam Millar",
            "Jacob Shaffelburg",
            "Tani Oluwaseyi",
            "Promise Akinpelu"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Haiti": {
        "coach": "S\u00e9bastien Mign\u00e9",
        "players": [
            "Alexandre Pierre",
            "Johny Placide",
            "Josu\u00e9 Duverger",
            "Carlens Arcus",
            "Jean-Kevin Duverne",
            "Hannes Delcroix",
            "Martin Exp\u00e9rience",
            "Ricardo Ad\u00e9",
            "Duke LaCroix",
            "Garven-Michee Metusala",
            "Keeto Thermoncy",
            "Wilguens Paugain",
            "Jean-Ricner Bellegarde",
            "Derrick Etienne",
            "Danley Jean Jacques",
            "Dominique Simon",
            "Carl Saint\u00e9",
            "Woodensky Pierre",
            "Duckens Nazon",
            "Frantzdy Pierrot",
            "Yassin Fortune",
            "Wilson Isidor",
            "Lenny Joseph",
            "Louicius Don Deedson",
            "Josu\u00e9 Casimir",
            "Ruben Providence"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Iran": {
        "coach": "Amir Ghalenoei",
        "players": [
            "Hossein Hosseini",
            "Payam Niazmand",
            "Alireza Beiranvand",
            "Ehsan Hajsafi",
            "Ramin Rezaeian",
            "Milad Mohammadi",
            "Hossein Kanaanizadegan",
            "Shojae Khalilzadeh",
            "Rouzbeh Cheshmi",
            "Saleh Hardani",
            "Ali Nemati",
            "Danial Eiri",
            "Saeid Ezatolahi",
            "Mehdi Torabi",
            "Mohammad Ghorbani",
            "Ariya Yousefi",
            "Medhi Ghayedi",
            "Amir Razzaghinia",
            "Alireza Jahanbakhsh",
            "Mehdi Taremi",
            "Dennis Eckert",
            "Ali Alipour",
            "Shahriar Moghanlou",
            "Mohammad Mohebi",
            "Saman Ghoddos",
            "Amir Hosseinzadeh"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Bosnia and Herzegovina": {
        "coach": "Sergej Barbarez",
        "players": [
            "Martin Zlomisli\u0107",
            "Nikola Vasilj",
            "Mladen Jurkas",
            "Sead Kola\u0161inac",
            "Dennis Had\u017eikaduni\u0107",
            "Nihad Mujaki\u0107",
            "Nikola Kati\u0107",
            "Stjepan Radelji\u0107",
            "Amar Dedi\u0107",
            "Tarik Muharemovi\u0107",
            "Arjan Malic",
            "D\u017eenis Burni\u0107",
            "Ivan \u0160unji\u0107",
            "Amir Had\u017eiahmetovi\u0107",
            "Armin Gigovic",
            "Ivan Ba\u0161i\u0107",
            "Benjamin Tahirovic",
            "Ermin Mahmic",
            "Amar Memi\u0107",
            "Edin D\u017eeko",
            "Jovo Luki\u0107",
            "Ermedin Demirovic",
            "Haris Tabakovi\u0107",
            "Samed Bazdar",
            "Esmir Bajraktarevic",
            "Kerim Alajbegovi\u0107"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Panama": {
        "coach": "Thomas Christiansen",
        "players": [
            "Luis Mej\u00eda",
            "Orlando Mosquera",
            "Cesar Samudio",
            "Roderick Miller",
            "Fidel Escobar",
            "\u00c9ric Davis",
            "Andr\u00e9s Andrade",
            "C\u00e9sar Blackman",
            "Jiovany Ramos",
            "Jos\u00e9 Cordoba",
            "Michael Murillo",
            "Edgardo Fari\u00f1a",
            "Jorge Guti\u00e9rrez",
            "Adalberto Carrasquilla",
            "Jos\u00e9 Luis Rodr\u00edguez",
            "Cecilio Waterman",
            "\u00c9dgar B\u00e1rcenas",
            "An\u00edbal Godoy",
            "Alberto Quintero",
            "Carlos Harvey",
            "C\u00e9sar Yanis",
            "Christian Martinez",
            "Jos\u00e9 Fajardo",
            "Ismael D\u00edaz",
            "Tomas Rodriguez",
            "Azarias Londo\u00f1o"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Cape Verde": {
        "coach": "Bubista",
        "players": [
            "M\u00e1rcio Rosa",
            "V\u00f3zinha",
            "C.J. dos Santos",
            "Steven Moreira",
            "Logan Costa",
            "Roberto Lopes",
            "Diney Borges",
            "Stopira",
            "Sidny Lopes Cabral",
            "Wagner Pina",
            "Kelvin Pires",
            "Deroy Duarte",
            "Garry Rodrigues",
            "Kevin Pina",
            "Laros Duarte",
            "Yannick Semedo",
            "Telmo Arcanjo",
            "Jamiro Monteiro",
            "Jo\u00e3o Paulo",
            "Willy Semedo",
            "Ryan Mendes",
            "Jovane Cabral",
            "Gilson Tavares",
            "Nuno Da Costa",
            "Dailon Rocha Livramento",
            "H\u00e9lio Varela"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "DR Congo": {
        "coach": "S\u00e9bastien Desabre",
        "players": [
            "Timothy Fayulu",
            "Lionel Mpasi",
            "Matthieu Epolo",
            "Axel Tuanzebe",
            "Chancel Mbemba",
            "Aaron Wan-Bissaka",
            "Arthur Masuaku",
            "Joris Kayembe",
            "Dylan Batubinsika",
            "G\u00e9d\u00e9on Kalulu",
            "Steve Kapuadi",
            "Ga\u00ebl Kakuta",
            "Samuel Moutoussamy",
            "Edo Kayembe",
            "Aaron Tshibola",
            "Charles Pickel",
            "Noah Sadiki",
            "Ngal'ayel Mukau",
            "Yoane Wissa",
            "Theo Bongonda",
            "C\u00e9dric Bakambu",
            "Simon Banza",
            "Nathanael Mbuku",
            "Meschack Elia",
            "Brian Cipenga",
            "Fiston Mayele"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Ivory Coast": {
        "coach": "Emerse Fa\u00e9",
        "players": [
            "Yahia Fofana",
            "Alban Lafont",
            "Mohamed Kone",
            "Evan N'Dicka",
            "Christopher Operi",
            "Ghislain Konan",
            "Wilfried Singo",
            "Guela Dou\u00e9",
            "Emmanuel Agbadou",
            "Odilon Kossounou",
            "Ousmane Diomande",
            "Franck Kessi\u00e9",
            "Seko Fofana",
            "Ibrahim Sangar\u00e9",
            "Jean Micha\u00ebl Seri",
            "Amad Diallo",
            "Parfait Guiagon",
            "Christ Ravynel Inao Oula\u00ef",
            "Nicolas P\u00e9p\u00e9",
            "Evann Guessand",
            "Ange-Yoan Bonny",
            "Sepe Elye Wahi",
            "Simon Adingra",
            "Oumar Diakite",
            "Bazoumana Tour\u00e9",
            "Yan Diomand\u00e9"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Qatar": {
        "coach": "Julen Lopetegui",
        "players": [
            "Salah Zakaria",
            "Meshaal Barsham",
            "Mahmoud Abunada",
            "Boualem Khoukhi",
            "Jassem Gaber Abdulsallam",
            "Homam Ahmed",
            "R\u00f3-R\u00f3",
            "Lucas Mendes",
            "Sultan Al Brake",
            "Hashemi Al Hussain",
            "Issa Laye",
            "Ayoub Al-Oui",
            "Assim Madibo",
            "Abdulaziz Hatem",
            "Karim Boudiaf",
            "Ahmed Fathy",
            "Yusuf Abdurisag",
            "Ahmed Al Ganehi",
            "Tahsin Jamshid",
            "Mohamed Al-Mannai",
            "Akram Afif",
            "Almoez Ali",
            "Mohammed Muntari",
            "Hassan Al Haydos",
            "Ahmed Alaa Eldin",
            "Edm\u00edlson"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Jordan": {
        "coach": "Unknown Coach",
        "players": [
            "Yazeed Abu Layla",
            "Abdallah Al Fakhouri",
            "Noureddin Bani Ateyah",
            "Ehsan Haddad",
            "Saleem Obaid",
            "Yazan Al Arab",
            "Mohammad Abualnadi",
            "Abdallah Naseeb",
            "Saed Al Rosan",
            "Husam Abu Dahab",
            "Anas Badawi",
            "Nizar Al Rashdan",
            "Rajaei Ayed",
            "Noor Al Rawabdeh",
            "Mohammad Abu Hasheesh",
            "Ibrahim Saadeh",
            "Mohammad Al-Dawoud",
            "Amer Jamous",
            "Musa Al Taamari",
            "Mahmoud Al Mardi",
            "Ali Olwan",
            "Mohannad Abu Taha",
            "Mohammad Abu Zrayq",
            "Ibrahim Sabra",
            "Odeh Fakhoury",
            "Ali Azaizeh"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Iraq": {
        "coach": "Graham Arnold",
        "players": [
            "Jalal Hassan",
            "Fahad Talib",
            "Ahmed Basil",
            "Hussein Ali",
            "Merchas Doski",
            "Rebin Sulaka",
            "Mustafa Saadoun",
            "Ahmed Yahya",
            "Frans Putros",
            "Zaid Tahseen",
            "Manaf Younis",
            "Akam Hashem",
            "Amir Al Ammari",
            "Kevin Yakob",
            "Aimar Sher",
            "Ibrahim Bayesh",
            "Youssef Amyn",
            "Ahmed Qasem",
            "Zidane Iqbal",
            "Zaid Ismail",
            "Aymen Hussein",
            "Ali Al-Hamadi",
            "Marko Farji",
            "Ali Jassim El-Aibi",
            "Mohanad Ali",
            "Ali Yousif"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Uzbekistan": {
        "coach": "Fabio Cannavaro",
        "players": [
            "Abduvakhid Nematov",
            "Botir Ergashev",
            "Utkir Yusupov",
            "Rustam Ashurmatov",
            "Umar Eshmurodov",
            "Abdukodir Khusanov",
            "Jakhongir O'rozov",
            "Farrukh Sayfiyev",
            "Khodjiakbar Alijonov",
            "Sherzod Nasrullayev",
            "Abdulla Abdullayev",
            "Bekhruz Karimov",
            "Avazbek Ulmasaliev",
            "Dostonbek Xamdamov",
            "Otabek Shukurov",
            "Oston Urunov",
            "Jamshid Iskanderov",
            "Akmal Mozgovoy",
            "Abbosbek Fayzullaev",
            "Azizjon Ganiev",
            "Odiljon Hamrobekov",
            "Sherzod Esanov",
            "Eldor Shomurodov",
            "Igor Sergeev",
            "Ruslanbek Jiyanov",
            "Azizbek Amonov"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Netherlands": {
        "coach": "Ronald Koeman",
        "players": [
            "Mark Flekken",
            "Bart Verbruggen",
            "Robin Roefs",
            "Denzel Dumfries",
            "Virgil van Dijk",
            "Nathan Ak\u00e9",
            "Jan Paul van Hecke",
            "Jurrien Timber",
            "Mickey van de Ven",
            "Jorrel Hato",
            "Marten de Roon",
            "Donyell Malen",
            "Frenkie de Jong",
            "Noa Lang",
            "Guus Til",
            "Teun Koopmeiners",
            "Tijjani Reijnders",
            "Ryan Gravenberch",
            "Mats Wieffer",
            "Quinten Timber",
            "Crysencio Summerville",
            "Cody Gakpo",
            "Justin Kluivert",
            "Wout Weghorst",
            "Memphis Depay",
            "Brian Brobbey"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Norway": {
        "coach": "St\u00e5le Solbakken",
        "players": [
            "\u00d8rjan Nyland",
            "Egil Selvik",
            "Sander Tangvik",
            "Kristoffer Ajer",
            "Torbj\u00f8rn Heggem",
            "Fredrik Bj\u00f8rkan",
            "Marcus Pedersen",
            "Julian Ryerson",
            "Leo \u00d8stig\u00e5rd",
            "Henrik Falchener",
            "Sondre Lang\u00e5s",
            "David Wolfe",
            "Morten Thorsby",
            "Martin \u00d8degaard",
            "Sander Berge",
            "Patrick Berg",
            "Fredrik Aursnes",
            "Kristian Thorstvedt",
            "Thelo Aasgaard",
            "Antonio Nusa",
            "Oscar Bobb",
            "Alexander S\u00f8rloth",
            "Jens Hauge",
            "Erling Haaland",
            "Andreas Schjelderup",
            "J\u00f8rgen Strand Larsen"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Scotland": {
        "coach": "Steve Clarke",
        "players": [
            "Angus Gunn",
            "Craig Gordon",
            "Liam Kelly",
            "Grant Hanley",
            "Dominic Hyam",
            "Andrew Robertson",
            "Kieran Tierney",
            "Jack Hendry",
            "Anthony Ralston",
            "John Souttar",
            "Scott McKenna",
            "Aaron Hickey",
            "Nathan Patterson",
            "Scott McTominay",
            "Kenny McLean",
            "Ryan Christie",
            "Lewis Ferguson",
            "John McGinn",
            "Ben Doak",
            "Findlay Curtis",
            "Tyler Fletcher",
            "Che Adams",
            "George Hirst",
            "Ross Stewart",
            "Lyndon Dykes",
            "Lawrence Shankland"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    },
    "Cura\u00e7ao": {
        "coach": "Dick Advocaat",
        "players": [
            "Trevor Doornbusch",
            "Eloy Room",
            "Tyrick Bodak",
            "Roshon van Eijma",
            "Joshua Brenet",
            "Armando Obispo",
            "Sheral Floranus",
            "Riechedly Bazoer",
            "Juri\u00ebn Gaari",
            "Shurandy Sambo",
            "Ar'jany Martha",
            "Livano Comenencia",
            "Deveron Fonville",
            "Tyrese Noslin",
            "Leandro Bacuna",
            "Godfried Roemeratoe",
            "Juninho Bacuna",
            "Kevin Felida",
            "Gervane Kastaneer",
            "Kenji Gorr\u00e9",
            "J\u00fcrgen Locadia",
            "Tahith Chong",
            "Sontje Hansen",
            "Jearl Margaritha",
            "Jeremy Antonisse",
            "Brandley Kuwas"
        ],
        "formation": "4-3-3",
        "style": "Balanced tactical approach."
    }
}

def generate_profiles():
    output_dir = os.path.join("docs", "team_profiles")
    os.makedirs(output_dir, exist_ok=True)
    
    for team, data in TEAMS_48.items():
        coach = data.get("coach", "Unknown Coach")
        # Ensure we handle empty squad cases just in case
        players = data.get("players", [])
        if not players:
            players = ["Unknown Player"]
            
        players_str = ", ".join(players)
        formation = data.get("formation", "4-3-3")
        style = data.get("style", "Balanced tactical approach")
        
        defensive_tactic = "Aggressive high block" if "press" in style.lower() else "Disciplined mid/low block"
        attacking_tactic = "Vertical and direct" if "direct" in style.lower() or "counter" in style.lower() else "Patient build-up and positional play"
        
        profile_content = f"""# Team Profile: {team}

## General Overview
- **Manager**: {coach}
- **Key Players**: {players_str}
- **Preferred Formation**: {formation}
- **Tactical Identity**: {style}

## Tactical Breakdown
### Attacking Phase
{team} implements a {attacking_tactic.lower()} approach. Operating primarily in a {formation} shape, the midfield looks to establish dominance early. When progressing the ball, they look for {players[0]} to act as the primary catalyst.

### Defensive Structure
Defensively, they utilize a {defensive_tactic.lower()}. The defensive line coordinates closely with the midfield pivot to deny space between the lines. {coach} demands extreme discipline out of possession.

### Transitions
In transition moments, {team} excels at immediate reactions. Offensively, they target the half-spaces instantly upon regaining the ball. Defensively, they attempt to cut off passing lanes and delay the opposition to reform their {formation} structure.
"""
        filepath = os.path.join(output_dir, f"{team.replace(' ', '_')}.md")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(profile_content)
            
    print(f"Successfully generated {len(TEAMS_48)} detailed tactical profiles in {output_dir}")

if __name__ == "__main__":
    generate_profiles()
